apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: prod
spec:
  selector:
    app: node-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: us.icr.io/durrani/node-app:1.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-storage
              mountPath: /app/data
          env:
            - name: DB_HOST
              value: mysql-service.database.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: icr-secret
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: node-app-pvc
